# Array in Python

To store 100 student marks we need to create hundred variables. but with one array variable we can store 100 student marks.
So array is an object that stores a group of elements of same datatype.

Array can store only one datatype. we cannot mix different datatypes in an array
we need not declare size of the array. it can grow dynamically


launch python shell using python or IDLE
>>help()
help>> array

## Advantages of Array

Advantages of array
Arrays are similar to lists. the main difference is that arrays can store only one type of elements whereas lists can store different type of elements.
when dealing with huge number of elements, arrays use less memory than lists and they offer faster execution than lists.
grows dynamically
syntax:

arrayname = array(type_code, [elements])

https://docs.python.org/3/library/array.html

## Array Creation

In [7]:
# creating an integer array

import array as ar
a = ar.array('i',[4,6,2,9])
print(type(a))

for x in a:
    print(x)

<class 'array.array'>
4
6
2
9

In [8]:
# creating array from another array
import array as ar
arr1=ar.array('d',[1.5,2.5,3.5])
print(arr1.typecode)
arr2=ar.array('d',(a*3 for a in arr1))

for i in arr2:
    print(i)

d
4.5
7.5
10.5

## Slicing Operations

In [9]:
# slicing operation
import array as ar
x=ar.array('i',[10,20,30,40])
print(x[1:4])
print(x[:4])
print(x[1:])
print(x[-3:])
print(x[1:5:2])

array('i', [20, 30, 40])
array('i', [10, 20, 30, 40])
array('i', [20, 30, 40])
array('i', [20, 30, 40])
array('i', [20, 40])

## Array Methods

In [10]:
# processing array
# Array class has several methods to process the Array
"""
.append
.extend
.fromfile
.tofile
.fromstring
.tostring
.fromlist
.tolist
.insert
.pop.
.remove
.reverse
"""

# A python program to understand various methods of array class
from array import *

arr= array('i',[10,20,30,40,50])
print('Original Array : ', arr)

#append 30 in the array arr:
arr.append(30)
arr.append(60)
print("After appending 30 and 60 are : ", arr)

# insert 99 at position 1
arr.insert(1,99)
print("After inserting 99 at the position 1 :", arr)

# remove 20 from the array
arr.remove(20)
print("After removing 20 from the array :",arr)

# remove the last element using pop method
arr.pop()
print("After removing the last element :", arr)

# finding the position of the element using index method
n=arr.index(30)
print("First occurence of element 30 is at ", n)

# convert array to list using .tolist() method
lst=arr.tolist()

print("list :",lst)
print("Array :", arr)

Original Array :  array('i', [10, 20, 30, 40, 50])
After appending 30 and 60 are :  array('i', [10, 20, 30, 40, 50, 30, 60])
After inserting 99 at the position 1 : array('i', [10, 99, 20, 30, 40, 50, 30, 60])
After removing 20 from the array : array('i', [10, 99, 30, 40, 50, 30, 60])
After removing the last element : array('i', [10, 99, 30, 40, 50, 30])
First occurence of element 30 is at  2
list : [10, 99, 30, 40, 50, 30]
Array : array('i', [10, 99, 30, 40, 50, 30])

## Advanatages of Array

# Arrays using NumPy(NUMeric PYthon)

NUMPY is library contains several functions to deal with scientific calculations like linear algebra, fourier transforms. 

It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices

Arrays which are created using NUMPY are called n-dimensional arrays. it can accepts only one datatype elements in an array

.

In [11]:
#Types of Arrays
# Single DImensional
# Multi Dimensional Arrays
import numpy as np
import array as arr
marks= arr.array('i',[74,75,97,80,66])
print("Marks Scored:", marks)

Marks Scored: array('i', [74, 75, 97, 80, 66])

## Creating arrays using different ways

1. using array function
it is function in the NUMPY module to create the array. we can specify the datatype. if you are not mentioning the datatype the interpreter finds the datatype from the data elements. it can be either int, float or character.
2. using linspace() --> linspace(start,stop,interval)
3. using logspace() --> similar to linspace but using logarithimical table
4. using arange()
5. using zeros() and ones() function

In [43]:
# Create an empty array
arr = np.empty((3,2))
print("Array 4 without any values-empty = \n", arr)

Array 4 without any values-empty =
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]

In [44]:
# Create a full array
arr= np.full((4,3,3),9)
print("Array 5 using FULL = \n", arr)

Array 5 using FULL =
 [[[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]]

In [45]:
import numpy as np
# Create an array of ones
arr=np.ones((3,3,4))
print("Array 1 using Ones = \n", arr)

# Create an array of zeros
arr=np.zeros((1,3,4),dtype=np.int16)
print("Array 2 using Zeros = \n", arr)

Array 1 using Ones =
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Array 2 using Zeros =
 [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

In [46]:
# creating array with values
arr= np.array([[1,1],[2,2]])
arr

array([[1, 1],
       [2, 2]])

In [38]:
# Create an array with random values
arr = np.random.random((2,2))
print("Array 3 using Random Values = \n", arr)

Array 3 using Random Values =
 [[0.92387037 0.13106079]
 [0.78810313 0.45115964]]

In [47]:
# Create an array of evenly-spaced values
arr = np.linspace(0,2,5)
print("Array 6 using LinSPace = \n", arr)

Array 6 using LinSPace =
 [0.  0.5 1.  1.5 2. ]

In [48]:
# Create an array using arange function
arr=np.arange(10,25,2)
print("Array 6 using arange() = \n", arr)

Array 6 using arange() =
 [10 12 14 16 18 20 22 24]

In [50]:
# Create an array of log-spaced values
arr = np.logspace(0,2,9)
print("Array 7 using LOGSPace = \n", arr)

Array 7 using LOGSPace =
 [  1.           1.77827941   3.16227766   5.62341325  10.
  17.7827941   31.6227766   56.23413252 100.        ]

In [51]:
# Create an array from another array
arr2=np.array(arr)
print("create array using another array = \n", arr2)

create array using another array =
 [  1.           1.77827941   3.16227766   5.62341325  10.
  17.7827941   31.6227766   56.23413252 100.        ]

## Mathematical operations on arrays

it is possible to mathematical operations like addition, subraction ... on the elements of array. 
to add array a and b we can do c= a+b. 
to divide array a with b c= a/b
these kind of operations on array are called vectorized opertions which is faster and compact.

Also we can mathematical functions on array using numpy

sin(arr)
cos(arr)
tan(arr)
log(arr)
abs(arr)
sqrt(arr)
power(arr,n)
exp(arr)
sum(arr)- sum of all elements
prod(arr)- prod of all elements
min(arr)
max(arr)

Also supports some statistical functions
mean(arr)
median(arr)
var(arr)
std(arr)
argmin(returns the index of the smallest elements in the array)
sort(arr)- gives the array with sorted elements

In [55]:
import numpy as np
arr = np.array([10,20,30.5,-40])
print(" Original Array:\t\t\t", arr)
print(" After adding  with  5:\t\t\t", arr+5)
print(" After multiply with 5:\t\t\t", arr*5)
print(" After modules  with 5:\t\t\t", arr%5)
print(" Using expression ::\t\t\t (arr+5)**2+10 ",(arr+5)**2+10)
print(" smallest element    ::\t\t\t",np.min(arr))
print(" mean element    ::\t\t\t",np.mean(arr))
print(" sort element    ::\t\t\t",np.sort(arr))

 Original Array:			 [ 10.   20.   30.5 -40. ]
 After adding  with  5:			 [ 15.   25.   35.5 -35. ]
 After multiply with 5:			 [  50.   100.   152.5 -200. ]
 After modules  with 5:			 [0.  0.  0.5 0. ]
 Using expression ::			 (arr+5)**2+10  [ 235.    635.   1270.25 1235.  ]
 smallest element    ::			 -40.0
 mean element    ::			 5.125
 sort element    ::			 [-40.   10.   20.   30.5]

## Comparing Arrays

In [58]:
# we can use the relational operators >,<=,==,!= to compare the arrays of same size. 
# it can compare the 2 arrays of same size and return the array of boolean values.
# use of any() and all()

import numpy as np
a = np.array([1,2,3,0])
b = np.array([0,2,3,1])
c = a>b
print(c)

# use of any() and all()
print("Check if ANY one element of array C is true---->", any(c))
print("Check if ALL one element of array C is true---->", all(c))

d = np.logical_and(a>0, a<4)
print("logical_and a>0 and a<4", d)
print(d)

d = np.logical_or(a>0, a<4)
print("logical_or a>0 and a<4", d)

[ True False False False]
Check if ANY one element of array C is true----> True
Check if ALL one element of array C is true----> False
logical_and a>0 and a<4 [ True  True  True False]
[ True  True  True False]
logical_or a>0 and a<4 [ True  True  True  True]

## Using WHERE

In [24]:
a = np.array([10,20,30,40,50],int)
b = np.array([1,21,3,40,51])

#if a is greater then take a else b
c= np.where(a>b, a,b)
print(c)

[10 21 30 40 51]

## Aliaing , Deep Copy and View

In [25]:
#  Aliasing the array
b=a
print(a,b)
a[0]=99
print("***")
print(a,b)
b

[10 20 30 40 50] [10 20 30 40 50]
***
[99 20 30 40 50] [99 20 30 40 50]

array([99, 20, 30, 40, 50])

In [27]:
##Deep Copy
a = np.array([1,2,3,0])
b = a.copy()
print("Deep Copy")
print(a)
print(b)
print(b is a)
b[0]=99
print(b)
print(a)

Deep Copy
[1 2 3 0]
[1 2 3 0]
False
[99  2  3  0]
[1 2 3 0]

In [26]:
# creating view

b=a.view() # it is also called as shallow copy.it is different from alias. it has separate memory. 
print(type(a))
print(type(b))

print(b is a)
print(b.base is a)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
False
True

## Slicing and indexing Numpy Arrays

In [28]:
# arrayname[Start,Stop,StepSize]
a=np.array([10,11,12,13,14,15])
print("array a slice a[1:6:2] is ", a[1:6:2])
print("array a slice a[::] is ", a[::])
print("array a slice a[2:] is ", a[2:])

## a[-1:-4:-1]

#n = number of elements
#i=start number
#j=stop number

#a[n+i,n+j,from right]
#print()
print("array a slice a[5:2:-1] is ", a[5:2:-1])

array a slice a[1:6:2] is  [11 13 15]
array a slice a[::] is  [10 11 12 13 14 15]
array a slice a[2:] is  [12 13 14 15]
array a slice a[5:2:-1] is  [15 14 13]

## n-dimensions and attributes

In [29]:
# Single dimensional Array
a=np.array([1,2,3,4])
print(a)
b=np.array([1,
            2,
            3,
            4])
print(b)
print(b.ndim)
# 2 dimensional arrays 2x4

c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.ndim)
# 3 dimensional arrays is combination of several 2d arrays

d=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])
print(d)
print(d.ndim)

[1 2 3 4]
[1 2 3 4]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]
3

In [30]:
# Attributes of array

# ndim  represents number of dimensions 1 for 1d array, 2 for 2d arrays, 3 for 3d

# shape attribute - gives the shape of an array

# Single dimensional Array
a=np.array([1,2])
print(a.shape)
# 2 dimensional arrays 2x4

c=np.array([[1,2,3],[4,5,6]])
print(" 2d Array",c)
print(c.shape)
# 3 dimensional arrays is combination of several 2d arrays

d=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])
print(d)
print(d.shape)

# Size Attribute gives number of elements in the array

print(d.size)

#itemsize attribute gives the memory size of the array element in bytes
print(d.itemsize)

#reshape()

#reshape method is useful to change the shape of the array
# the new array should have the same number of elements of the original array

arr1= np.arange(10)
print(arr1)
arr2=arr1.reshape(5,2)
print(arr2)

# Flatten method
print(arr2.flatten())

(2,)
 2d Array [[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]
(2, 2, 3)
12
8
[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]

In [31]:
# multidimensional arrays
# 2d and 3d arrays are called as multidimensional arrays
# 2d array is also called as Matrix. mxn m is number of rows and n is number of columns

# multidimensional array can be created using following methods

# 1. array()
# 2. ones() and zeros()
# 3. eye()
# 4. reshape()

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.ones((2,3),int)
print(b)
c = np.zeros((2,3),int)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]